import { Application } from "../../application";
import { Constants } from "../../constants";
import { insertSpacesBetweenCapitalizedWords } from "../../utils/text-utils";
import { CustomProperty } from "../custom-property";
import { PinCategory } from "./pin-category";
import { PinContainerType } from "./pin-container-type";
import { PinDirection } from "./pin-direction";
import { PinLink } from "./pin-link";

export class PinProperty extends CustomProperty {

    id: string;
    name: string;
    friendlyName: string;
    category: PinCategory;

    nodeName: string;

    direction: PinDirection;
    toolTip: string;

    subCategory: string;
    subCategoryObject: string;
    subCategoryMemberReference: string;

    containerType: PinContainerType;

    isReference: boolean;
    isConst: boolean;
    isWeakPointer: boolean;
    isUObjectWrapper: boolean;

    linkedTo: PinLink[];
    persistentGUID: string;
    hidden: boolean;
    notConnectable: boolean;

    valueType?: string;

    defaultValue: any;
    autogeneratedDefaultValue: string;
    defaultValueIsReadOnly: boolean;

    // Used for knots
    defaultValueIsIgnored: boolean;

    advancedView: boolean;
    orphanedPin: boolean;

    hideName: boolean;

    constructor(nodeName: string) {
        super();
        this.nodeName = nodeName;
        this.direction = PinDirection.EGPD_Input;
    }

    get isLinked(): boolean {
        return (this.linkedTo && this.linkedTo.length > 0);
    }

    public get formattedName(): string {
        if (this.hideName) { return ''; }
        if (this.friendlyName) {
            return this.friendlyName;
        }

        return this.name;
    }

    public get shouldDrawDefaultValueBox(): boolean {
        return (!this.isLinked && this.direction !== PinDirection.EGPD_Output && !!this.defaultValue);
    }

    public getUniqueName() {
        return this.nodeName + " " + this.id;
    }
}
